luxonis/depthai-shared

include/depthai-shared/datatype/DatatypeEnum.hpp
include/depthai-shared/datatype/RawImageManipConfig.hpp
include/depthai-shared/datatype/RawImgFrame.hpp
include/depthai-shared/pb/properties/ImageManipProperties.hpp
include/depthai-shared/pb/properties/XLinkInProperties.hpp
include/depthai-shared/pb/properties/XLinkOutProperties.hpp
src/datatype/DatatypeEnum.cpp

Updated ImgFrame frame buffer types, to accomodate for a broader variety. Added ImageManipConfig which sets current manipulation configuration to be applied on input image.

Gen2 - ImageManip node

---

include/depthai-shared/pb/properties/ColorCameraProperties.hpp
include/depthai-shared/pb/properties/MonoCameraProperties.hpp
include/depthai-shared/pb/properties/StereoDepthProperties.hpp
pipeline_builder/nodes/MonoCamera/MonoCamera.json
pipeline_builder/nodes/MonoCamera/MonoCamera.properties.schema.json
pipeline_builder/nodes/StereoDepth/StereoDepth.json
pipeline_builder/nodes/StereoDepth/StereoDepth.properties.schema.json

To be merged to `gen2` after PR https://github.com/luxonis/depthai-shared/pull/9

Gen2: add MonoCamera and StereoDepth nodes

---

include/depthai-shared/common/Timestamp.hpp
include/depthai-shared/datatype/DatatypeEnum.hpp
include/depthai-shared/datatype/RawSystemInformation.hpp
include/depthai-shared/pb/common/ChipTemperature.hpp
include/depthai-shared/pb/common/CpuUsage.hpp
include/depthai-shared/pb/common/MemoryInfo.hpp
include/depthai-shared/pb/properties/SystemLoggerProperties.hpp
src/datatype/DatatypeEnum.cpp

- Added a couple of common structures like: `MemoryInfo, CpuUsage, ChipTemperature`.
- Added `SystemInformation` message
- Added `SystemLogger` node properties

Gen2 improvements

---

.gitignore
include/depthai-shared/datatype/RawImageManipConfig.hpp
include/depthai-shared/datatype/RawSystemInformation.hpp
include/depthai-shared/properties/XLinkOutProperties.hpp

Added keepAspectRatio property
Added CMX memory usage retriever

ImageManip improvements

---

include/depthai-shared/datatype/RawSpatialLocations.hpp

Added new field: `depthAveragePixelCount`

Spatial data extension

---

include/depthai-shared/common/UsbSpeed.hpp

Added UsbSpeed enum

---

include/depthai-shared/datatype/RawSpatialLocationCalculatorConfig.hpp
include/depthai-shared/datatype/RawSpatialLocations.hpp

Added spatial calculator improvements

Spatial calculator improvements

---

include/depthai-shared/datatype/DatatypeEnum.hpp
include/depthai-shared/datatype/RawEdgeDetectorConfig.hpp
include/depthai-shared/datatype/RawImgFrame.hpp
include/depthai-shared/properties/EdgeDetectorProperties.hpp
src/datatype/DatatypeEnum.cpp

Add EdgeDetector node

---

include/depthai-shared/datatype/RawIMUData.hpp

Fixes https://github.com/luxonis/depthai-shared/issues/45

Fix imu accuracy name clash

---

include/depthai-shared/properties/ObjectTrackerProperties.hpp

Added as:
```
SHORT_TERM_KCF
SHORT_TERM_IMAGELESS
```

Object tracker fixes, updates: 2 new tracking modes: KCF, short-term imageless.

---

include/depthai-shared/datatype/RawCameraControl.hpp

- Added manual white balance (color temperature) camera control
- Code changes: https://github.com/luxonis/depthai-shared/pull/69

Release v2.13.3

---

include/depthai-shared/datatype/RawStereoDepthConfig.hpp
include/depthai-shared/properties/StereoDepthProperties.hpp

Implemented filters:
- Spatial
- Temporal
- Speckle
- Decimation
- Threshold

Stereo post processing

---

include/depthai-shared/properties/ScriptProperties.hpp

To mitigate crashes when running on MSS.

Change default CPU to CSS for Script node

---

include/depthai-shared/datatype/RawStereoDepthConfig.hpp

Described here: https://github.com/luxonis/depthai-python/pull/615

StereoDepth: Add option for disparity shift

---

include/depthai-shared/datatype/RawCameraControl.hpp

so Sphinx can automatically pull from this and show in docs.

Added camera control specifications 

---

include/depthai-shared/properties/DetectionNetworkProperties.hpp
include/depthai-shared/properties/NeuralNetworkProperties.hpp

Needed for the PR at depthai-core: https://github.com/luxonis/depthai-core/pull/560

Support for neural network and detection network on S3

---

include/depthai-shared/properties/MonoCameraProperties.hpp

- MonoCameraProperties: add frame pool size config

ir_frame_control

---

include/depthai-shared/datatype/RawSpatialImgDetections.hpp

Went with composition instead inheritence

Expand spatial image detections with original config

---

include/depthai-shared/datatype/RawSpatialLocationCalculatorConfig.hpp
include/depthai-shared/datatype/RawSpatialLocations.hpp
include/depthai-shared/properties/SpatialDetectionNetworkProperties.hpp

RFC: namings
TODO before merge: set default median

Spatial location calculator: Add mode and median options

---

include/depthai-shared/device/BoardConfig.hpp
include/depthai-shared/properties/StereoDepthProperties.hpp

StereoDepth: Add support for full FOV depth

---

include/depthai-shared/common/TensorInfo.hpp

Added quantization information + convince functions to get the tensor width/height.

Rvc3 detection parser refactor

---

include/depthai-shared/common/Point2f.hpp
include/depthai-shared/common/Point3f.hpp
include/depthai-shared/common/Rect.hpp
include/depthai-shared/common/Size2f.hpp

- partial fix luxonis/depthai-core#247

fix var hides class member, constructors with this->
