src/xlink/xlink_wrapper.cpp

Creating multiple depthai devices caused XLink to be reinitialized, invalidating prior device resources.

Prevent XLinkWrapper from errantly reinitializing XLink

---

include/depthai-shared/metadata/frame_metadata.hpp

The uninitialized `instNo` metadata field caused `getCameraName()` to possibly segfault.
Adding the check, even though the device side should be fixed now.

FrameMetadata getCameraName(): check for out-of-range instNo

---

include/depthai-shared/xlink/xlink_wrapper.hpp
src/xlink/xlink_wrapper.cpp

Modified `initFromHostSide` to take `usb_speed` and `mx_serial` strings as arguments(pass by reference) which are private variables of device class. allowing them to be loaded on XLink connection.

Fetching USB speed and Myriad X serial number

---

include/depthai-shared/datatype/DatatypeEnum.hpp
include/depthai-shared/datatype/RawCameraControl.hpp
include/depthai-shared/pb/common/CameraBoardSocket.hpp
include/depthai-shared/pb/properties/ColorCameraProperties.hpp
include/depthai-shared/pb/properties/MonoCameraProperties.hpp
src/datatype/DatatypeEnum.cpp

- Added new message type `CameraControl` which will be expanded with additional camera related control commands. For now there is a command for still capturing.
- Added CameraBoardSocket enum which describes boards physical connectors instead of their IDs
- Added ColorCamera options to specify initial crop and video and still output sizes

Gen2 camera improvements

---

include/depthai-shared/pb/common/CameraImageOrientation.hpp
include/depthai-shared/pb/properties/ColorCameraProperties.hpp
include/depthai-shared/pb/properties/MonoCameraProperties.hpp

```
AUTO   // on OAK-1/megaAI: ROTATE_180_DEG, other boards: NORMAL
NORMAL
HORIZONTAL_MIRROR
VERTICAL_FLIP
ROTATE_180_DEG
```

Add CameraImageOrientation config to Color/Mono properties

---

include/depthai-shared/datatype/RawBuffer.hpp
include/depthai-shared/datatype/RawCameraControl.hpp
include/depthai-shared/datatype/RawIMUData.hpp
include/depthai-shared/datatype/RawImageManipConfig.hpp
include/depthai-shared/datatype/RawImgDetections.hpp
include/depthai-shared/datatype/RawImgFrame.hpp
include/depthai-shared/datatype/RawNNData.hpp
include/depthai-shared/datatype/RawSpatialImgDetections.hpp
include/depthai-shared/datatype/RawSpatialLocationCalculatorConfig.hpp
include/depthai-shared/datatype/RawSpatialLocations.hpp
include/depthai-shared/datatype/RawSystemInformation.hpp
include/depthai-shared/datatype/RawTracklets.hpp

Required for suggestion by @themarpe on https://github.com/luxonis/depthai-core/pull/150

Make `datatype::serialize` a const member function

---

include/depthai-shared/common/CameraBoardSocket.hpp
src/datatype/DatatypeEnum.cpp

On some compilers (like AppleClang on macOS), the change here requires the standard to be set to at least C++14. This will be updated in [depthai-core](https://github.com/luxonis/depthai-core).
Discussion here: https://github.com/luxonis/depthai-shared/pull/19#discussion_r630290051

Remove build helper for `unordered_map` of `enum class` key

---

include/depthai-shared/datatype/RawImgFrame.hpp

While trying setting GREY8 as ImageManip output it returned error.
ImgFrame types enum is out of sync with FW side.
Grey8 still doesn't work though in ImgManip, but that's something else.

Synchronize ImgFrame types order with FW

---

include/depthai-shared/datatype/RawImgFrame.hpp

This is useful to debug the host-device time sync mechanism, as sometimes jumps of few milliseconds were observed.

RawImgFrame: add `tsDevice` - direct device timestamp

---

include/depthai-shared/properties/GlobalProperties.hpp

/**
* Chunk size for splitting device-sent XLink packets, in bytes. A larger value could
* increase performance, with 0 disabling chunking. A negative value won't modify the
* device defaults - configured per protocol, currently 64*1024 for both USB and Ethernet.
*/
int32_t xlinkChunkSize = -1;

Configure XLink chunk size

---

include/depthai-shared/datatype/RawFeatureTrackerConfig.hpp
include/depthai-shared/device/PrebootConfig.hpp

partial fix luxonis/depthai-core#248
Working towards reducing hundreds of warnings about truncations. This PR and forthcoming PR for `depthai-core` remove many many hundreds of warnings of truncations and mismatched var length/sizes. The goal is to reduce the noise so warnings that need action can be surfaced.

fix constant/var truncates to decrease noise

---

include/depthai-shared/common/Point2f.hpp
include/depthai-shared/common/Point3f.hpp
include/depthai-shared/common/Rect.hpp
include/depthai-shared/common/Size2f.hpp

Marked constructors as `default` and assigned initialization values to some of the common types
Addresses: https://github.com/luxonis/depthai-core/issues/249

Modified constructors of some common types

---

include/depthai-shared/datatype/RawEdgeDetectorConfig.hpp
include/depthai-shared/datatype/RawSpatialLocationCalculatorConfig.hpp
include/depthai-shared/datatype/RawSpatialLocations.hpp
include/depthai-shared/datatype/RawStereoDepthConfig.hpp

Colons `:` and dots `.` seems to throw it off.

Modified docstrings to better work with stubgen

---

include/depthai-shared/device/PrebootConfig.hpp

- Fix an issue with watchdog timeout being overridden to 1.5s for Ethernet case. Normally the device will choose 1.5s for USB, 4s for Ethernet. Might have been a cause for watchdog induced crashes in case of network congestion, but not confirmed.
- Add `watchdogInitialDelayMs` to PrebootConfig, for the host to set optionally and override the device defaults, currently 8s for USB, 15s for Ethernet.

Config watchdog initial delay

---

include/depthai-shared/utility/Serialization.hpp

Fon non-CMake consumption, to provide users with a better error message.
Version 3.9.0 is minimum required for the used nlohmann macros for serialization

Specify minimum nlohmann json version

---

include/depthai-shared/device/BoardConfig.hpp

Due to recursive include of the header file itself: `BoardConfig.hpp`
(clang 13, Ubuntu 21.10)

Fix build error: error: redefinition of 'BOARD_CONFIG_MAGIC1'

---

include/depthai-shared/datatype/RawImgFrame.hpp

This is coordinated work for fix luxonis/depthai-core#282
When ImgFrame is default constructed, it has a type of YUV422i because the enum at 0 is `YUV422i`.
full details https://github.com/luxonis/depthai-core/issues/282#issuecomment-1039808395

init dai::RawImgFrame::Specs::type = NONE

---

include/depthai-shared/properties/ScriptProperties.hpp

fixes #97
removes the unneeded init of `std::string` to `""`

removes unneeded init of `std::string` to `""`

---

include/depthai-shared/datatype/RawIMUData.hpp

so API is the same across different messages. Thougts?

Added getSequenceNum to IMU report, 

---

include/depthai-shared/properties/StereoDepthProperties.hpp

To avoid artifacts in stereo matching, due to replicated pixels.
TODO: mask the depth map for invalid pixels in rectified image

Stereo rectify: Change edge color fill from pixel replication to 0 (black)

---

include/depthai-shared/datatype/RawStereoDepthConfig.hpp

/**
* Brightness filtering.
* If input frame pixel is too dark or too bright, disparity will be invalidated.
* The idea is that for too dark/too bright pixels we have low confidence,
* since that area was under/over exposed and details were lost.
*/

Implement brightness filter

---

include/depthai-shared/common/StereoRectification.hpp

Removes breaking changes relative to latest EEPROM, namely vertical rectifciation matrices.

Revert vertical stereo in CalibrationHandler

---

include/depthai-shared/device/BoardConfig.hpp
include/depthai-shared/properties/CameraProperties.hpp
include/depthai-shared/properties/ColorCameraProperties.hpp
include/depthai-shared/properties/MonoCameraProperties.hpp

CC: @themarpe whether adding to BoardConfig can break POE with older bootloader?

Add 3A skipping option to reduce CSS CPU usage

---

include/depthai-shared/datatype/RawCameraControl.hpp
include/depthai-shared/properties/ColorCameraProperties.hpp

- miscellaneous camera controls, to be documented
- new ColorCamera resolutions for full FoV with binning/scaling:
- IMX582: 2000 × 1500
- IMX378/477/577: 2028 × 1520
- IMX214: 2104 × 1560

RVC3 misc camera controls, ColorCamera binned full FoV res
